[2023-06-18 15:29:53,930] {scheduler_job.py:182} INFO - Started process (PID=47) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 15:29:53,940] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 15:29:53,952] {logging_mixin.py:104} INFO - [2023-06-18 15:29:53,951] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:29:54,957] {logging_mixin.py:104} INFO - [2023-06-18 15:29:54,956] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 15:29:55,369] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:29:55,505] {logging_mixin.py:104} INFO - [2023-06-18 15:29:55,504] {dag.py:1818} INFO - Sync 1 DAGs
[2023-06-18 15:29:55,591] {logging_mixin.py:104} INFO - [2023-06-18 15:29:55,591] {dag.py:1837} INFO - Creating ORM DAG for etl_dag
[2023-06-18 15:29:55,642] {logging_mixin.py:104} INFO - [2023-06-18 15:29:55,641] {dag.py:2273} INFO - Setting next_dagrun for etl_dag to 2023-06-17 00:00:00+00:00
[2023-06-18 15:29:55,726] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 1.834 seconds
[2023-06-18 15:30:25,940] {scheduler_job.py:182} INFO - Started process (PID=49) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 15:30:25,947] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 15:30:25,950] {logging_mixin.py:104} INFO - [2023-06-18 15:30:25,950] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:30:26,449] {logging_mixin.py:104} INFO - [2023-06-18 15:30:26,448] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 15:30:26,643] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:30:26,710] {logging_mixin.py:104} INFO - [2023-06-18 15:30:26,709] {dag.py:1818} INFO - Sync 1 DAGs
[2023-06-18 15:30:26,767] {logging_mixin.py:104} INFO - [2023-06-18 15:30:26,766] {dag.py:2273} INFO - Setting next_dagrun for etl_dag to 2023-06-17 00:00:00+00:00
[2023-06-18 15:30:26,800] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.876 seconds
[2023-06-18 15:30:57,003] {scheduler_job.py:182} INFO - Started process (PID=51) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 15:30:57,013] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 15:30:57,018] {logging_mixin.py:104} INFO - [2023-06-18 15:30:57,018] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:30:57,800] {logging_mixin.py:104} INFO - [2023-06-18 15:30:57,799] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 15:30:58,207] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:30:58,397] {logging_mixin.py:104} INFO - [2023-06-18 15:30:58,395] {dag.py:1818} INFO - Sync 1 DAGs
[2023-06-18 15:30:58,535] {logging_mixin.py:104} INFO - [2023-06-18 15:30:58,535] {dag.py:2273} INFO - Setting next_dagrun for etl_dag to 2023-06-17 00:00:00+00:00
[2023-06-18 15:30:58,627] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 1.651 seconds
[2023-06-18 15:31:28,952] {scheduler_job.py:182} INFO - Started process (PID=53) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 15:31:28,958] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 15:31:28,962] {logging_mixin.py:104} INFO - [2023-06-18 15:31:28,962] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:31:29,398] {logging_mixin.py:104} INFO - [2023-06-18 15:31:29,398] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 15:31:29,603] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:31:29,670] {logging_mixin.py:104} INFO - [2023-06-18 15:31:29,669] {dag.py:1818} INFO - Sync 1 DAGs
[2023-06-18 15:31:29,721] {logging_mixin.py:104} INFO - [2023-06-18 15:31:29,721] {dag.py:2273} INFO - Setting next_dagrun for etl_dag to 2023-06-17 00:00:00+00:00
[2023-06-18 15:31:29,748] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.813 seconds
[2023-06-18 15:31:59,855] {scheduler_job.py:182} INFO - Started process (PID=55) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 15:31:59,860] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 15:31:59,863] {logging_mixin.py:104} INFO - [2023-06-18 15:31:59,863] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:32:00,356] {logging_mixin.py:104} INFO - [2023-06-18 15:32:00,355] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 15:32:00,546] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:32:00,620] {logging_mixin.py:104} INFO - [2023-06-18 15:32:00,619] {dag.py:1818} INFO - Sync 1 DAGs
[2023-06-18 15:32:00,671] {logging_mixin.py:104} INFO - [2023-06-18 15:32:00,670] {dag.py:2273} INFO - Setting next_dagrun for etl_dag to None
[2023-06-18 15:32:00,694] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.853 seconds
[2023-06-18 15:32:31,362] {scheduler_job.py:182} INFO - Started process (PID=57) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 15:32:31,366] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 15:32:31,369] {logging_mixin.py:104} INFO - [2023-06-18 15:32:31,368] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:32:31,787] {logging_mixin.py:104} INFO - [2023-06-18 15:32:31,786] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 15:32:31,966] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:32:32,022] {logging_mixin.py:104} INFO - [2023-06-18 15:32:32,022] {dag.py:1818} INFO - Sync 1 DAGs
[2023-06-18 15:32:32,070] {logging_mixin.py:104} INFO - [2023-06-18 15:32:32,069] {dag.py:2273} INFO - Setting next_dagrun for etl_dag to None
[2023-06-18 15:32:32,085] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.737 seconds
[2023-06-18 15:33:02,517] {scheduler_job.py:182} INFO - Started process (PID=59) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 15:33:02,524] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 15:33:02,526] {logging_mixin.py:104} INFO - [2023-06-18 15:33:02,526] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:33:02,931] {logging_mixin.py:104} INFO - [2023-06-18 15:33:02,930] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 15:33:03,141] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:33:03,201] {logging_mixin.py:104} INFO - [2023-06-18 15:33:03,200] {dag.py:1818} INFO - Sync 1 DAGs
[2023-06-18 15:33:03,244] {logging_mixin.py:104} INFO - [2023-06-18 15:33:03,243] {dag.py:2273} INFO - Setting next_dagrun for etl_dag to None
[2023-06-18 15:33:03,264] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.761 seconds
[2023-06-18 15:33:33,637] {scheduler_job.py:182} INFO - Started process (PID=61) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 15:33:33,642] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 15:33:33,644] {logging_mixin.py:104} INFO - [2023-06-18 15:33:33,644] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:33:34,071] {logging_mixin.py:104} INFO - [2023-06-18 15:33:34,070] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 15:33:34,248] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:33:34,337] {logging_mixin.py:104} INFO - [2023-06-18 15:33:34,336] {dag.py:1818} INFO - Sync 1 DAGs
[2023-06-18 15:33:34,398] {logging_mixin.py:104} INFO - [2023-06-18 15:33:34,398] {dag.py:2273} INFO - Setting next_dagrun for etl_dag to None
[2023-06-18 15:33:34,420] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.794 seconds
[2023-06-18 15:34:04,805] {scheduler_job.py:182} INFO - Started process (PID=63) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 15:34:04,815] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 15:34:04,824] {logging_mixin.py:104} INFO - [2023-06-18 15:34:04,824] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:34:05,292] {logging_mixin.py:104} INFO - [2023-06-18 15:34:05,292] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 15:34:05,469] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:34:05,543] {logging_mixin.py:104} INFO - [2023-06-18 15:34:05,542] {dag.py:1818} INFO - Sync 1 DAGs
[2023-06-18 15:34:05,586] {logging_mixin.py:104} INFO - [2023-06-18 15:34:05,586] {dag.py:2273} INFO - Setting next_dagrun for etl_dag to None
[2023-06-18 15:34:05,612] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.823 seconds
[2023-06-18 15:34:36,252] {scheduler_job.py:182} INFO - Started process (PID=65) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 15:34:36,257] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 15:34:36,260] {logging_mixin.py:104} INFO - [2023-06-18 15:34:36,259] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:34:36,704] {logging_mixin.py:104} INFO - [2023-06-18 15:34:36,703] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 15:34:36,924] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:34:37,000] {logging_mixin.py:104} INFO - [2023-06-18 15:34:37,000] {dag.py:1818} INFO - Sync 1 DAGs
[2023-06-18 15:34:37,051] {logging_mixin.py:104} INFO - [2023-06-18 15:34:37,051] {dag.py:2273} INFO - Setting next_dagrun for etl_dag to None
[2023-06-18 15:34:37,080] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.841 seconds
[2023-06-18 15:35:07,823] {scheduler_job.py:182} INFO - Started process (PID=67) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 15:35:07,831] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 15:35:07,837] {logging_mixin.py:104} INFO - [2023-06-18 15:35:07,836] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:35:08,233] {logging_mixin.py:104} INFO - [2023-06-18 15:35:08,232] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 15:35:08,413] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:35:08,479] {logging_mixin.py:104} INFO - [2023-06-18 15:35:08,478] {dag.py:1818} INFO - Sync 1 DAGs
[2023-06-18 15:35:08,534] {logging_mixin.py:104} INFO - [2023-06-18 15:35:08,534] {dag.py:2273} INFO - Setting next_dagrun for etl_dag to None
[2023-06-18 15:35:08,564] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.765 seconds
[2023-06-18 15:35:39,067] {scheduler_job.py:182} INFO - Started process (PID=69) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 15:35:39,073] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 15:35:39,076] {logging_mixin.py:104} INFO - [2023-06-18 15:35:39,075] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:35:39,519] {logging_mixin.py:104} INFO - [2023-06-18 15:35:39,519] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 15:35:39,707] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:35:39,781] {logging_mixin.py:104} INFO - [2023-06-18 15:35:39,780] {dag.py:1818} INFO - Sync 1 DAGs
[2023-06-18 15:35:39,829] {logging_mixin.py:104} INFO - [2023-06-18 15:35:39,829] {dag.py:2273} INFO - Setting next_dagrun for etl_dag to None
[2023-06-18 15:35:39,858] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.807 seconds
[2023-06-18 15:36:10,258] {scheduler_job.py:182} INFO - Started process (PID=71) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 15:36:10,263] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 15:36:10,266] {logging_mixin.py:104} INFO - [2023-06-18 15:36:10,265] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:36:10,701] {logging_mixin.py:104} INFO - [2023-06-18 15:36:10,701] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 15:36:10,898] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:36:10,960] {logging_mixin.py:104} INFO - [2023-06-18 15:36:10,960] {dag.py:1818} INFO - Sync 1 DAGs
[2023-06-18 15:36:11,009] {logging_mixin.py:104} INFO - [2023-06-18 15:36:11,009] {dag.py:2273} INFO - Setting next_dagrun for etl_dag to None
[2023-06-18 15:36:11,052] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.804 seconds
[2023-06-18 15:36:41,252] {scheduler_job.py:182} INFO - Started process (PID=73) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 15:36:41,256] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 15:36:41,259] {logging_mixin.py:104} INFO - [2023-06-18 15:36:41,259] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:36:41,684] {logging_mixin.py:104} INFO - [2023-06-18 15:36:41,684] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 15:36:41,890] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:36:41,977] {logging_mixin.py:104} INFO - [2023-06-18 15:36:41,976] {dag.py:1818} INFO - Sync 1 DAGs
[2023-06-18 15:36:42,055] {logging_mixin.py:104} INFO - [2023-06-18 15:36:42,055] {dag.py:2273} INFO - Setting next_dagrun for etl_dag to None
[2023-06-18 15:36:42,095] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.854 seconds
[2023-06-18 15:37:12,488] {scheduler_job.py:182} INFO - Started process (PID=75) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 15:37:12,492] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 15:37:12,494] {logging_mixin.py:104} INFO - [2023-06-18 15:37:12,494] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:37:12,969] {logging_mixin.py:104} INFO - [2023-06-18 15:37:12,968] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 15:37:13,150] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:37:13,213] {logging_mixin.py:104} INFO - [2023-06-18 15:37:13,212] {dag.py:1818} INFO - Sync 1 DAGs
[2023-06-18 15:37:13,269] {logging_mixin.py:104} INFO - [2023-06-18 15:37:13,268] {dag.py:2273} INFO - Setting next_dagrun for etl_dag to None
[2023-06-18 15:37:13,294] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.816 seconds
[2023-06-18 15:37:50,709] {scheduler_job.py:182} INFO - Started process (PID=46) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 15:37:50,724] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 15:37:50,756] {logging_mixin.py:104} INFO - [2023-06-18 15:37:50,748] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:37:51,919] {logging_mixin.py:104} INFO - [2023-06-18 15:37:51,907] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 15:37:52,469] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:37:52,685] {logging_mixin.py:104} INFO - [2023-06-18 15:37:52,683] {dag.py:1818} INFO - Sync 1 DAGs
[2023-06-18 15:37:52,806] {logging_mixin.py:104} INFO - [2023-06-18 15:37:52,805] {dag.py:2273} INFO - Setting next_dagrun for etl_dag to None
[2023-06-18 15:37:52,884] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 2.217 seconds
[2023-06-18 15:38:23,024] {scheduler_job.py:182} INFO - Started process (PID=48) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 15:38:23,031] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 15:38:23,035] {logging_mixin.py:104} INFO - [2023-06-18 15:38:23,035] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:38:23,721] {logging_mixin.py:104} INFO - [2023-06-18 15:38:23,720] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 15:38:23,940] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:38:24,038] {logging_mixin.py:104} INFO - [2023-06-18 15:38:24,038] {dag.py:1818} INFO - Sync 1 DAGs
[2023-06-18 15:38:24,098] {logging_mixin.py:104} INFO - [2023-06-18 15:38:24,097] {dag.py:2273} INFO - Setting next_dagrun for etl_dag to None
[2023-06-18 15:38:24,129] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 1.135 seconds
[2023-06-18 15:38:54,567] {scheduler_job.py:182} INFO - Started process (PID=50) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 15:38:54,584] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 15:38:54,597] {logging_mixin.py:104} INFO - [2023-06-18 15:38:54,597] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:38:55,213] {logging_mixin.py:104} INFO - [2023-06-18 15:38:55,213] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 15:38:55,453] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:38:55,554] {logging_mixin.py:104} INFO - [2023-06-18 15:38:55,554] {dag.py:1818} INFO - Sync 1 DAGs
[2023-06-18 15:38:55,611] {logging_mixin.py:104} INFO - [2023-06-18 15:38:55,611] {dag.py:2273} INFO - Setting next_dagrun for etl_dag to None
[2023-06-18 15:38:55,640] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 1.098 seconds
[2023-06-18 15:39:25,907] {scheduler_job.py:182} INFO - Started process (PID=52) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 15:39:25,912] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 15:39:25,918] {logging_mixin.py:104} INFO - [2023-06-18 15:39:25,917] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:39:26,550] {logging_mixin.py:104} INFO - [2023-06-18 15:39:26,549] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 15:39:26,792] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:39:26,899] {logging_mixin.py:104} INFO - [2023-06-18 15:39:26,899] {dag.py:1818} INFO - Sync 1 DAGs
[2023-06-18 15:39:27,023] {logging_mixin.py:104} INFO - [2023-06-18 15:39:27,023] {dag.py:2273} INFO - Setting next_dagrun for etl_dag to None
[2023-06-18 15:39:27,054] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 1.160 seconds
[2023-06-18 15:39:57,337] {scheduler_job.py:182} INFO - Started process (PID=54) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 15:39:57,346] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 15:39:57,353] {logging_mixin.py:104} INFO - [2023-06-18 15:39:57,351] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:39:57,845] {logging_mixin.py:104} INFO - [2023-06-18 15:39:57,844] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 15:39:58,035] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:39:58,105] {logging_mixin.py:104} INFO - [2023-06-18 15:39:58,105] {dag.py:1818} INFO - Sync 1 DAGs
[2023-06-18 15:39:58,156] {logging_mixin.py:104} INFO - [2023-06-18 15:39:58,156] {dag.py:2273} INFO - Setting next_dagrun for etl_dag to None
[2023-06-18 15:39:58,182] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.857 seconds
[2023-06-18 15:40:28,498] {scheduler_job.py:182} INFO - Started process (PID=56) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 15:40:28,503] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 15:40:28,506] {logging_mixin.py:104} INFO - [2023-06-18 15:40:28,506] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:40:29,019] {logging_mixin.py:104} INFO - [2023-06-18 15:40:29,018] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 15:40:29,236] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:40:29,303] {logging_mixin.py:104} INFO - [2023-06-18 15:40:29,302] {dag.py:1818} INFO - Sync 1 DAGs
[2023-06-18 15:40:29,365] {logging_mixin.py:104} INFO - [2023-06-18 15:40:29,364] {dag.py:2273} INFO - Setting next_dagrun for etl_dag to None
[2023-06-18 15:40:29,435] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.961 seconds
[2023-06-18 15:41:00,197] {scheduler_job.py:182} INFO - Started process (PID=58) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 15:41:00,201] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 15:41:00,206] {logging_mixin.py:104} INFO - [2023-06-18 15:41:00,204] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:41:00,709] {logging_mixin.py:104} INFO - [2023-06-18 15:41:00,708] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 15:41:00,895] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:41:00,975] {logging_mixin.py:104} INFO - [2023-06-18 15:41:00,975] {dag.py:1818} INFO - Sync 1 DAGs
[2023-06-18 15:41:01,018] {logging_mixin.py:104} INFO - [2023-06-18 15:41:01,017] {dag.py:2273} INFO - Setting next_dagrun for etl_dag to None
[2023-06-18 15:41:01,039] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.856 seconds
[2023-06-18 15:41:31,581] {scheduler_job.py:182} INFO - Started process (PID=60) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 15:41:31,586] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 15:41:31,589] {logging_mixin.py:104} INFO - [2023-06-18 15:41:31,589] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:41:32,022] {logging_mixin.py:104} INFO - [2023-06-18 15:41:32,022] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 15:41:32,196] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:41:32,265] {logging_mixin.py:104} INFO - [2023-06-18 15:41:32,265] {dag.py:1818} INFO - Sync 1 DAGs
[2023-06-18 15:41:32,309] {logging_mixin.py:104} INFO - [2023-06-18 15:41:32,309] {dag.py:2273} INFO - Setting next_dagrun for etl_dag to None
[2023-06-18 15:41:32,330] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.764 seconds
[2023-06-18 15:42:02,788] {scheduler_job.py:182} INFO - Started process (PID=62) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 15:42:02,793] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 15:42:02,795] {logging_mixin.py:104} INFO - [2023-06-18 15:42:02,795] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:42:03,189] {logging_mixin.py:104} INFO - [2023-06-18 15:42:03,188] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 15:42:03,365] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:42:03,430] {logging_mixin.py:104} INFO - [2023-06-18 15:42:03,430] {dag.py:1818} INFO - Sync 1 DAGs
[2023-06-18 15:42:03,476] {logging_mixin.py:104} INFO - [2023-06-18 15:42:03,475] {dag.py:2273} INFO - Setting next_dagrun for etl_dag to None
[2023-06-18 15:42:03,498] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.734 seconds
[2023-06-18 15:42:33,698] {scheduler_job.py:182} INFO - Started process (PID=64) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 15:42:33,704] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 15:42:33,707] {logging_mixin.py:104} INFO - [2023-06-18 15:42:33,707] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:42:34,097] {logging_mixin.py:104} INFO - [2023-06-18 15:42:34,096] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 15:42:34,287] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:42:34,345] {logging_mixin.py:104} INFO - [2023-06-18 15:42:34,344] {dag.py:1818} INFO - Sync 1 DAGs
[2023-06-18 15:42:34,390] {logging_mixin.py:104} INFO - [2023-06-18 15:42:34,390] {dag.py:2273} INFO - Setting next_dagrun for etl_dag to None
[2023-06-18 15:42:34,407] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.720 seconds
[2023-06-18 15:43:04,979] {scheduler_job.py:182} INFO - Started process (PID=66) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 15:43:04,985] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 15:43:04,988] {logging_mixin.py:104} INFO - [2023-06-18 15:43:04,988] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:43:05,470] {logging_mixin.py:104} INFO - [2023-06-18 15:43:05,469] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 15:43:05,645] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:43:05,722] {logging_mixin.py:104} INFO - [2023-06-18 15:43:05,722] {dag.py:1818} INFO - Sync 1 DAGs
[2023-06-18 15:43:05,766] {logging_mixin.py:104} INFO - [2023-06-18 15:43:05,765] {dag.py:2273} INFO - Setting next_dagrun for etl_dag to None
[2023-06-18 15:43:05,788] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.823 seconds
[2023-06-18 15:43:36,157] {scheduler_job.py:182} INFO - Started process (PID=68) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 15:43:36,162] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 15:43:36,166] {logging_mixin.py:104} INFO - [2023-06-18 15:43:36,165] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:43:36,589] {logging_mixin.py:104} INFO - [2023-06-18 15:43:36,589] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 15:43:36,780] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:43:36,864] {logging_mixin.py:104} INFO - [2023-06-18 15:43:36,863] {dag.py:1818} INFO - Sync 1 DAGs
[2023-06-18 15:43:36,908] {logging_mixin.py:104} INFO - [2023-06-18 15:43:36,908] {dag.py:2273} INFO - Setting next_dagrun for etl_dag to None
[2023-06-18 15:43:36,949] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.811 seconds
[2023-06-18 15:44:07,455] {scheduler_job.py:182} INFO - Started process (PID=70) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 15:44:07,462] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 15:44:07,466] {logging_mixin.py:104} INFO - [2023-06-18 15:44:07,465] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:44:07,883] {logging_mixin.py:104} INFO - [2023-06-18 15:44:07,883] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 15:44:08,076] {logging_mixin.py:104} INFO - [2023-06-18 15:44:08,068] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 41, in <module>
    dag = etl_dag(origin = 'NYC', destination = 'CHI', time_delta = 10)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 2318, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/etl_dag.py", line 35, in etl_dag
    departure_date = generate_departure_date(time_delta = time_delta)
TypeError: generate_departure_date() got an unexpected keyword argument 'time_delta'
[2023-06-18 15:44:08,079] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:44:08,130] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.689 seconds
[2023-06-18 15:44:38,543] {scheduler_job.py:182} INFO - Started process (PID=72) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 15:44:38,548] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 15:44:38,551] {logging_mixin.py:104} INFO - [2023-06-18 15:44:38,551] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:44:38,987] {logging_mixin.py:104} INFO - [2023-06-18 15:44:38,987] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 15:44:39,170] {logging_mixin.py:104} INFO - [2023-06-18 15:44:39,163] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 41, in <module>
    dag = etl_dag(origin = 'NYC', destination = 'CHI', time_delta = 10)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 2318, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/etl_dag.py", line 35, in etl_dag
    departure_date = generate_departure_date(time_delta = time_delta)
TypeError: generate_departure_date() got an unexpected keyword argument 'time_delta'
[2023-06-18 15:44:39,173] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:44:39,217] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.686 seconds
[2023-06-18 15:45:09,343] {scheduler_job.py:182} INFO - Started process (PID=74) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 15:45:09,348] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 15:45:09,352] {logging_mixin.py:104} INFO - [2023-06-18 15:45:09,351] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:45:09,787] {logging_mixin.py:104} INFO - [2023-06-18 15:45:09,786] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 15:45:09,949] {logging_mixin.py:104} INFO - [2023-06-18 15:45:09,943] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 41, in <module>
    dag = etl_dag(origin = 'NYC', destination = 'CHI', time_delta = 10)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 2318, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/etl_dag.py", line 35, in etl_dag
    departure_date = generate_departure_date(time_delta = time_delta)
TypeError: generate_departure_date() got an unexpected keyword argument 'time_delta'
[2023-06-18 15:45:09,951] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:45:09,980] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.653 seconds
[2023-06-18 15:45:40,330] {scheduler_job.py:182} INFO - Started process (PID=76) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 15:45:40,333] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 15:45:40,336] {logging_mixin.py:104} INFO - [2023-06-18 15:45:40,335] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:45:40,726] {logging_mixin.py:104} INFO - [2023-06-18 15:45:40,726] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 15:45:40,889] {logging_mixin.py:104} INFO - [2023-06-18 15:45:40,883] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 41, in <module>
    dag = etl_dag(origin = 'NYC', destination = 'CHI', time_delta = 10)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 2318, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/etl_dag.py", line 35, in etl_dag
    departure_date = generate_departure_date(time_delta = time_delta)
TypeError: generate_departure_date() got an unexpected keyword argument 'time_delta'
[2023-06-18 15:45:40,892] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:45:40,924] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.602 seconds
[2023-06-18 15:46:11,490] {scheduler_job.py:182} INFO - Started process (PID=78) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 15:46:11,494] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 15:46:11,496] {logging_mixin.py:104} INFO - [2023-06-18 15:46:11,496] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:46:11,905] {logging_mixin.py:104} INFO - [2023-06-18 15:46:11,904] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 15:46:12,070] {logging_mixin.py:104} INFO - [2023-06-18 15:46:12,064] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 39, in <module>
    dag = etl_dag(origin = 'NYC', destination = 'CHI', time_delta = 10)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 2318, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/etl_dag.py", line 33, in etl_dag
    departure_date = generate_departure_date(time_delta = time_delta)
TypeError: generate_departure_date() got an unexpected keyword argument 'time_delta'
[2023-06-18 15:46:12,072] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:46:12,111] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.630 seconds
[2023-06-18 15:46:42,502] {scheduler_job.py:182} INFO - Started process (PID=80) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 15:46:42,507] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 15:46:42,510] {logging_mixin.py:104} INFO - [2023-06-18 15:46:42,509] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:46:42,898] {logging_mixin.py:104} INFO - [2023-06-18 15:46:42,897] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 15:46:43,072] {logging_mixin.py:104} INFO - [2023-06-18 15:46:43,065] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 39, in <module>
    dag = etl_dag(origin = 'NYC', destination = 'CHI', time_delta = 10)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 2318, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/etl_dag.py", line 33, in etl_dag
    departure_date = generate_departure_date(days = time_delta)
  File "/opt/airflow/dags/utils.py", line 9, in generate_departure_date
    delta = timedelta(days=days)
TypeError: unsupported type for timedelta days component: DagParam
[2023-06-18 15:46:43,074] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:46:43,106] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.617 seconds
[2023-06-18 15:47:13,485] {scheduler_job.py:182} INFO - Started process (PID=82) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 15:47:13,490] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 15:47:13,492] {logging_mixin.py:104} INFO - [2023-06-18 15:47:13,492] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:47:13,894] {logging_mixin.py:104} INFO - [2023-06-18 15:47:13,894] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 15:47:14,077] {logging_mixin.py:104} INFO - [2023-06-18 15:47:14,070] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 39, in <module>
    dag = etl_dag(origin = 'NYC', destination = 'CHI', time_delta = 10)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 2318, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/etl_dag.py", line 33, in etl_dag
    departure_date = generate_departure_date(days = time_delta)
  File "/opt/airflow/dags/utils.py", line 9, in generate_departure_date
    delta = timedelta(days=days)
TypeError: unsupported type for timedelta days component: DagParam
[2023-06-18 15:47:14,080] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:47:14,117] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.642 seconds
[2023-06-18 15:47:44,606] {scheduler_job.py:182} INFO - Started process (PID=84) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 15:47:44,611] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 15:47:44,613] {logging_mixin.py:104} INFO - [2023-06-18 15:47:44,613] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:47:45,010] {logging_mixin.py:104} INFO - [2023-06-18 15:47:45,008] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 15:47:45,223] {logging_mixin.py:104} INFO - [2023-06-18 15:47:45,216] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 39, in <module>
    dag = etl_dag(origin = 'NYC', destination = 'CHI', time_delta = 10)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 2318, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/etl_dag.py", line 33, in etl_dag
    departure_date = generate_departure_date(days = time_delta)
  File "/opt/airflow/dags/utils.py", line 9, in generate_departure_date
    delta = timedelta(days=days)
TypeError: unsupported type for timedelta days component: DagParam
[2023-06-18 15:47:45,225] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:47:45,258] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.668 seconds
[2023-06-18 15:48:11,377] {scheduler_job.py:182} INFO - Started process (PID=46) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 15:48:11,388] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 15:48:11,403] {logging_mixin.py:104} INFO - [2023-06-18 15:48:11,398] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:48:12,147] {logging_mixin.py:104} INFO - [2023-06-18 15:48:12,146] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 15:48:12,356] {logging_mixin.py:104} INFO - [2023-06-18 15:48:12,345] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 39, in <module>
    dag = etl_dag(origin = 'NYC', destination = 'CHI', time_delta = 10)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 2318, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/etl_dag.py", line 33, in etl_dag
    departure_date = generate_departure_date(days = time_delta)
  File "/opt/airflow/dags/utils.py", line 9, in generate_departure_date
    delta = timedelta(days=days)
TypeError: unsupported type for timedelta days component: DagParam
[2023-06-18 15:48:12,371] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:48:12,455] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 1.125 seconds
[2023-06-18 15:48:42,709] {scheduler_job.py:182} INFO - Started process (PID=48) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 15:48:42,716] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 15:48:42,723] {logging_mixin.py:104} INFO - [2023-06-18 15:48:42,722] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:48:43,337] {logging_mixin.py:104} INFO - [2023-06-18 15:48:43,335] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 15:48:43,558] {logging_mixin.py:104} INFO - [2023-06-18 15:48:43,542] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 39, in <module>
    dag = etl_dag(origin = 'NYC', destination = 'CHI', time_delta = 10)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 2318, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/etl_dag.py", line 33, in etl_dag
    departure_date = generate_departure_date(days = time_delta)
  File "/opt/airflow/dags/utils.py", line 9, in generate_departure_date
    delta = timedelta(days=days)
TypeError: unsupported type for timedelta days component: DagParam
[2023-06-18 15:48:43,562] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:48:43,605] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.911 seconds
[2023-06-18 15:49:14,059] {scheduler_job.py:182} INFO - Started process (PID=50) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 15:49:14,069] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 15:49:14,088] {logging_mixin.py:104} INFO - [2023-06-18 15:49:14,087] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:49:14,763] {logging_mixin.py:104} INFO - [2023-06-18 15:49:14,763] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 15:49:15,057] {logging_mixin.py:104} INFO - [2023-06-18 15:49:15,036] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 39, in <module>
    dag = etl_dag(origin = 'NYC', destination = 'CHI', time_delta = 10)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 2318, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/etl_dag.py", line 33, in etl_dag
    departure_date = generate_departure_date(days = time_delta)
  File "/opt/airflow/dags/utils.py", line 9, in generate_departure_date
    delta = timedelta(days=days)
TypeError: unsupported type for timedelta days component: DagParam
[2023-06-18 15:49:15,062] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:49:15,115] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 1.089 seconds
[2023-06-18 15:49:45,600] {scheduler_job.py:182} INFO - Started process (PID=52) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 15:49:45,605] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 15:49:45,609] {logging_mixin.py:104} INFO - [2023-06-18 15:49:45,608] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:49:46,016] {logging_mixin.py:104} INFO - [2023-06-18 15:49:46,015] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 15:49:46,181] {logging_mixin.py:104} INFO - [2023-06-18 15:49:46,174] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 39, in <module>
    dag = etl_dag(origin = 'NYC', destination = 'CHI', time_delta = 10)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 2318, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/etl_dag.py", line 33, in etl_dag
    departure_date = generate_departure_date(days = time_delta)
  File "/opt/airflow/dags/utils.py", line 9, in generate_departure_date
    delta = timedelta(days=days)
TypeError: unsupported type for timedelta days component: DagParam
[2023-06-18 15:49:46,184] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:49:46,227] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.640 seconds
[2023-06-18 15:50:16,559] {scheduler_job.py:182} INFO - Started process (PID=54) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 15:50:16,566] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 15:50:16,569] {logging_mixin.py:104} INFO - [2023-06-18 15:50:16,569] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:50:17,063] {logging_mixin.py:104} INFO - [2023-06-18 15:50:17,063] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 15:50:17,230] {logging_mixin.py:104} INFO - [2023-06-18 15:50:17,222] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 39, in <module>
    dag = etl_dag(origin = 'NYC', destination = 'CHI', time_delta = 10)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 2318, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/etl_dag.py", line 33, in etl_dag
    departure_date = generate_departure_date(days = time_delta)
  File "/opt/airflow/dags/utils.py", line 9, in generate_departure_date
    delta = timedelta(days=days)
TypeError: unsupported type for timedelta days component: DagParam
[2023-06-18 15:50:17,233] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:50:17,276] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.738 seconds
[2023-06-18 15:50:47,810] {scheduler_job.py:182} INFO - Started process (PID=56) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 15:50:47,815] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 15:50:47,817] {logging_mixin.py:104} INFO - [2023-06-18 15:50:47,817] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:50:48,244] {logging_mixin.py:104} INFO - [2023-06-18 15:50:48,243] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 15:50:48,429] {logging_mixin.py:104} INFO - [2023-06-18 15:50:48,421] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 39, in <module>
    dag = etl_dag(origin = 'NYC', destination = 'CHI', time_delta = 10)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 2318, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/etl_dag.py", line 33, in etl_dag
    departure_date = generate_departure_date(days = time_delta)
  File "/opt/airflow/dags/utils.py", line 9, in generate_departure_date
    delta = timedelta(days=days)
TypeError: unsupported type for timedelta days component: DagParam
[2023-06-18 15:50:48,431] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:50:48,468] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.668 seconds
[2023-06-18 15:51:18,783] {scheduler_job.py:182} INFO - Started process (PID=58) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 15:51:18,789] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 15:51:18,791] {logging_mixin.py:104} INFO - [2023-06-18 15:51:18,791] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:51:19,214] {logging_mixin.py:104} INFO - [2023-06-18 15:51:19,213] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 15:51:19,442] {logging_mixin.py:104} INFO - [2023-06-18 15:51:19,424] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 39, in <module>
    dag = etl_dag(origin = 'NYC', destination = 'CHI', time_delta = 10)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 2318, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/etl_dag.py", line 33, in etl_dag
    departure_date = generate_departure_date(days = time_delta)
  File "/opt/airflow/dags/utils.py", line 9, in generate_departure_date
    delta = timedelta(days=days)
TypeError: unsupported type for timedelta days component: DagParam
[2023-06-18 15:51:19,450] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:51:19,495] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.724 seconds
[2023-06-18 15:51:49,892] {scheduler_job.py:182} INFO - Started process (PID=60) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 15:51:49,899] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 15:51:49,902] {logging_mixin.py:104} INFO - [2023-06-18 15:51:49,901] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:51:50,294] {logging_mixin.py:104} INFO - [2023-06-18 15:51:50,293] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 15:51:50,461] {logging_mixin.py:104} INFO - [2023-06-18 15:51:50,453] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 39, in <module>
    dag = etl_dag(origin = 'NYC', destination = 'CHI', time_delta = 10)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 2318, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/etl_dag.py", line 33, in etl_dag
    departure_date = generate_departure_date(days = time_delta)
  File "/opt/airflow/dags/utils.py", line 9, in generate_departure_date
    delta = timedelta(days=days)
TypeError: unsupported type for timedelta days component: DagParam
[2023-06-18 15:51:50,463] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:51:50,495] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.617 seconds
[2023-06-18 15:52:20,830] {scheduler_job.py:182} INFO - Started process (PID=62) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 15:52:20,834] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 15:52:20,837] {logging_mixin.py:104} INFO - [2023-06-18 15:52:20,836] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:52:21,252] {logging_mixin.py:104} INFO - [2023-06-18 15:52:21,252] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 15:52:21,538] {logging_mixin.py:104} INFO - [2023-06-18 15:52:21,526] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 39, in <module>
    dag = etl_dag(origin = 'NYC', destination = 'CHI', time_delta = 10)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 2318, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/etl_dag.py", line 33, in etl_dag
    departure_date = generate_departure_date(days = time_delta)
  File "/opt/airflow/dags/utils.py", line 9, in generate_departure_date
    delta = timedelta(days=days)
TypeError: unsupported type for timedelta days component: DagParam
[2023-06-18 15:52:21,542] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:52:21,601] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.781 seconds
[2023-06-18 15:52:52,071] {scheduler_job.py:182} INFO - Started process (PID=64) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 15:52:52,077] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 15:52:52,081] {logging_mixin.py:104} INFO - [2023-06-18 15:52:52,080] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:52:52,528] {logging_mixin.py:104} INFO - [2023-06-18 15:52:52,528] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 15:52:52,733] {logging_mixin.py:104} INFO - [2023-06-18 15:52:52,726] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 39, in <module>
    dag = etl_dag(origin = 'NYC', destination = 'CHI', days = 10)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 2318, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/etl_dag.py", line 33, in etl_dag
    departure_date = generate_departure_date(days = days)
  File "/opt/airflow/dags/utils.py", line 9, in generate_departure_date
    delta = timedelta(days=days)
TypeError: unsupported type for timedelta days component: DagParam
[2023-06-18 15:52:52,735] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:52:52,781] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.722 seconds
[2023-06-18 15:53:22,883] {scheduler_job.py:182} INFO - Started process (PID=66) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 15:53:22,888] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 15:53:22,891] {logging_mixin.py:104} INFO - [2023-06-18 15:53:22,890] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:53:23,291] {logging_mixin.py:104} INFO - [2023-06-18 15:53:23,290] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 15:53:23,495] {logging_mixin.py:104} INFO - [2023-06-18 15:53:23,484] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 39, in <module>
    dag = etl_dag(origin = 'NYC', destination = 'CHI', days = 10)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 2318, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/etl_dag.py", line 33, in etl_dag
    departure_date = generate_departure_date(days = days)
  File "/opt/airflow/dags/utils.py", line 9, in generate_departure_date
    delta = timedelta(days=days)
TypeError: unsupported type for timedelta days component: DagParam
[2023-06-18 15:53:23,497] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:53:23,538] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.673 seconds
[2023-06-18 15:53:53,701] {scheduler_job.py:182} INFO - Started process (PID=68) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 15:53:53,707] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 15:53:53,710] {logging_mixin.py:104} INFO - [2023-06-18 15:53:53,709] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:53:54,210] {logging_mixin.py:104} INFO - [2023-06-18 15:53:54,209] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 15:53:54,406] {logging_mixin.py:104} INFO - [2023-06-18 15:53:54,398] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 39, in <module>
    dag = etl_dag(origin = 'NYC', destination = 'CHI', days = 10)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 2318, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/etl_dag.py", line 33, in etl_dag
    departure_date = generate_departure_date(days = days)
  File "/opt/airflow/dags/utils.py", line 9, in generate_departure_date
    delta = timedelta(days=days)
TypeError: unsupported type for timedelta days component: DagParam
[2023-06-18 15:53:54,409] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:53:54,467] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.782 seconds
[2023-06-18 15:54:49,064] {scheduler_job.py:182} INFO - Started process (PID=45) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 15:54:49,072] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 15:54:49,080] {logging_mixin.py:104} INFO - [2023-06-18 15:54:49,078] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:54:49,714] {logging_mixin.py:104} INFO - [2023-06-18 15:54:49,713] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 15:54:49,956] {logging_mixin.py:104} INFO - [2023-06-18 15:54:49,936] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 39, in <module>
    dag = etl_dag(origin = 'NYC', destination = 'CHI', days = 10)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 2318, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/etl_dag.py", line 32, in etl_dag
    breakpoint()
NameError: name 'breakpoint' is not defined
[2023-06-18 15:54:49,961] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:54:50,075] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 1.031 seconds
[2023-06-18 15:54:51,755] {scheduler_job.py:182} INFO - Started process (PID=47) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 15:54:51,765] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 15:54:51,776] {logging_mixin.py:104} INFO - [2023-06-18 15:54:51,776] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:54:52,451] {logging_mixin.py:104} INFO - [2023-06-18 15:54:52,449] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 15:54:52,659] {logging_mixin.py:104} INFO - [2023-06-18 15:54:52,648] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 39, in <module>
    dag = etl_dag(origin = 'NYC', destination = 'CHI', days = 10)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 2318, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/etl_dag.py", line 32, in etl_dag
    breakpoint()
NameError: name 'breakpoint' is not defined
[2023-06-18 15:54:52,672] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:54:52,734] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 1.007 seconds
[2023-06-18 15:55:23,078] {scheduler_job.py:182} INFO - Started process (PID=49) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 15:55:23,089] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 15:55:23,094] {logging_mixin.py:104} INFO - [2023-06-18 15:55:23,093] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:55:23,725] {logging_mixin.py:104} INFO - [2023-06-18 15:55:23,724] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 15:55:24,077] {logging_mixin.py:104} INFO - [2023-06-18 15:55:24,061] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 39, in <module>
    dag = etl_dag(origin = 'NYC', destination = 'CHI', days = 10)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 2318, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/etl_dag.py", line 32, in etl_dag
    breakpoint()
NameError: name 'breakpoint' is not defined
[2023-06-18 15:55:24,089] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:55:24,135] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 1.170 seconds
[2023-06-18 15:55:54,316] {scheduler_job.py:182} INFO - Started process (PID=51) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 15:55:54,325] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 15:55:54,329] {logging_mixin.py:104} INFO - [2023-06-18 15:55:54,328] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:55:55,335] {logging_mixin.py:104} INFO - [2023-06-18 15:55:55,334] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 15:55:55,634] {logging_mixin.py:104} INFO - [2023-06-18 15:55:55,615] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 38, in <module>
    dag = etl_dag(origin = 'NYC', destination = 'CHI', days = 10)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 2318, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/etl_dag.py", line 32, in etl_dag
    departure_date = generate_departure_date(days = days)
  File "/opt/airflow/dags/utils.py", line 9, in generate_departure_date
    delta = timedelta(days=days)
TypeError: unsupported type for timedelta days component: DagParam
[2023-06-18 15:55:55,642] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:55:55,700] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 1.407 seconds
[2023-06-18 15:56:25,997] {scheduler_job.py:182} INFO - Started process (PID=53) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 15:56:26,010] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 15:56:26,019] {logging_mixin.py:104} INFO - [2023-06-18 15:56:26,018] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:56:26,552] {logging_mixin.py:104} INFO - [2023-06-18 15:56:26,552] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 15:56:26,752] {logging_mixin.py:104} INFO - [2023-06-18 15:56:26,744] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 38, in <module>
    dag = etl_dag(origin = 'NYC', destination = 'CHI', days = 10)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 2318, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/etl_dag.py", line 32, in etl_dag
    departure_date = generate_departure_date(days = days)
  File "/opt/airflow/dags/utils.py", line 9, in generate_departure_date
    delta = timedelta(days=days)
TypeError: unsupported type for timedelta days component: DagParam
[2023-06-18 15:56:26,754] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:56:26,790] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.822 seconds
[2023-06-18 15:56:57,266] {scheduler_job.py:182} INFO - Started process (PID=55) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 15:56:57,271] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 15:56:57,274] {logging_mixin.py:104} INFO - [2023-06-18 15:56:57,274] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:56:57,674] {logging_mixin.py:104} INFO - [2023-06-18 15:56:57,673] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 15:56:57,846] {logging_mixin.py:104} INFO - [2023-06-18 15:56:57,839] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 38, in <module>
    dag = etl_dag(origin = 'NYC', destination = 'CHI', days = 10)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 2318, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/etl_dag.py", line 32, in etl_dag
    departure_date = generate_departure_date(days = days)
  File "/opt/airflow/dags/utils.py", line 9, in generate_departure_date
    delta = timedelta(days=days)
TypeError: unsupported type for timedelta days component: DagParam
[2023-06-18 15:56:57,848] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:56:57,879] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.628 seconds
[2023-06-18 15:57:28,252] {scheduler_job.py:182} INFO - Started process (PID=57) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 15:57:28,259] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 15:57:28,263] {logging_mixin.py:104} INFO - [2023-06-18 15:57:28,262] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:57:28,704] {logging_mixin.py:104} INFO - [2023-06-18 15:57:28,703] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 15:57:28,882] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:57:28,955] {logging_mixin.py:104} INFO - [2023-06-18 15:57:28,954] {dag.py:1818} INFO - Sync 1 DAGs
[2023-06-18 15:57:29,019] {logging_mixin.py:104} INFO - [2023-06-18 15:57:29,019] {dag.py:2273} INFO - Setting next_dagrun for etl_dag to None
[2023-06-18 15:57:29,052] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.815 seconds
[2023-06-18 15:57:59,350] {scheduler_job.py:182} INFO - Started process (PID=59) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 15:57:59,362] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 15:57:59,365] {logging_mixin.py:104} INFO - [2023-06-18 15:57:59,365] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:57:59,824] {logging_mixin.py:104} INFO - [2023-06-18 15:57:59,822] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 15:58:00,122] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:58:00,215] {logging_mixin.py:104} INFO - [2023-06-18 15:58:00,214] {dag.py:1818} INFO - Sync 1 DAGs
[2023-06-18 15:58:00,267] {logging_mixin.py:104} INFO - [2023-06-18 15:58:00,267] {dag.py:2273} INFO - Setting next_dagrun for etl_dag to None
[2023-06-18 15:58:00,289] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.953 seconds
[2023-06-18 15:58:30,850] {scheduler_job.py:182} INFO - Started process (PID=61) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 15:58:30,857] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 15:58:30,860] {logging_mixin.py:104} INFO - [2023-06-18 15:58:30,859] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:58:31,284] {logging_mixin.py:104} INFO - [2023-06-18 15:58:31,283] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 15:58:31,467] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:58:31,533] {logging_mixin.py:104} INFO - [2023-06-18 15:58:31,532] {dag.py:1818} INFO - Sync 1 DAGs
[2023-06-18 15:58:31,578] {logging_mixin.py:104} INFO - [2023-06-18 15:58:31,578] {dag.py:2273} INFO - Setting next_dagrun for etl_dag to None
[2023-06-18 15:58:31,599] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.763 seconds
[2023-06-18 15:59:02,037] {scheduler_job.py:182} INFO - Started process (PID=63) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 15:59:02,042] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 15:59:02,044] {logging_mixin.py:104} INFO - [2023-06-18 15:59:02,044] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:59:02,417] {logging_mixin.py:104} INFO - [2023-06-18 15:59:02,417] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 15:59:02,624] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:59:02,698] {logging_mixin.py:104} INFO - [2023-06-18 15:59:02,698] {dag.py:1818} INFO - Sync 1 DAGs
[2023-06-18 15:59:02,743] {logging_mixin.py:104} INFO - [2023-06-18 15:59:02,743] {dag.py:2273} INFO - Setting next_dagrun for etl_dag to None
[2023-06-18 15:59:02,766] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.743 seconds
[2023-06-18 15:59:33,065] {scheduler_job.py:182} INFO - Started process (PID=65) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 15:59:33,069] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 15:59:33,071] {logging_mixin.py:104} INFO - [2023-06-18 15:59:33,071] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:59:33,479] {logging_mixin.py:104} INFO - [2023-06-18 15:59:33,479] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 15:59:33,666] {logging_mixin.py:104} INFO - [2023-06-18 15:59:33,660] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 39, in <module>
    dag = etl_dag(origin = 'NYC', destination = 'CHI')
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 2318, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/etl_dag.py", line 33, in etl_dag
    departure_date = generate_departure_date(time_delta_days = 14)
TypeError: generate_departure_date() got an unexpected keyword argument 'time_delta_days'
[2023-06-18 15:59:33,669] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 15:59:33,704] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.651 seconds
[2023-06-18 16:00:04,390] {scheduler_job.py:182} INFO - Started process (PID=67) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 16:00:04,394] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 16:00:04,397] {logging_mixin.py:104} INFO - [2023-06-18 16:00:04,396] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 16:00:04,818] {logging_mixin.py:104} INFO - [2023-06-18 16:00:04,817] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 16:00:05,007] {logging_mixin.py:104} INFO - [2023-06-18 16:00:05,000] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 40, in <module>
    dag = etl_dag(origin = 'NYC', destination = 'CHI')
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 2318, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/etl_dag.py", line 34, in etl_dag
    departure_date = generate_departure_date(time_delta = time_delta_days)
TypeError: generate_departure_date() got an unexpected keyword argument 'time_delta'
[2023-06-18 16:00:05,010] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 16:00:05,056] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.674 seconds
[2023-06-18 16:00:35,434] {scheduler_job.py:182} INFO - Started process (PID=69) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 16:00:35,438] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 16:00:35,440] {logging_mixin.py:104} INFO - [2023-06-18 16:00:35,440] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 16:00:35,857] {logging_mixin.py:104} INFO - [2023-06-18 16:00:35,857] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 16:00:36,021] {logging_mixin.py:104} INFO - [2023-06-18 16:00:36,015] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 40, in <module>
    dag = etl_dag(origin = 'NYC', destination = 'CHI')
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 2318, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/etl_dag.py", line 34, in etl_dag
    departure_date = generate_departure_date(time_delta = time_delta_days)
TypeError: generate_departure_date() got an unexpected keyword argument 'time_delta'
[2023-06-18 16:00:36,023] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 16:00:36,060] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.635 seconds
[2023-06-18 16:01:27,590] {scheduler_job.py:182} INFO - Started process (PID=46) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 16:01:27,604] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 16:01:27,612] {logging_mixin.py:104} INFO - [2023-06-18 16:01:27,611] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 16:01:28,495] {logging_mixin.py:104} INFO - [2023-06-18 16:01:28,495] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 16:01:29,061] {logging_mixin.py:104} INFO - [2023-06-18 16:01:29,053] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 40, in <module>
    dag = etl_dag(origin = 'NYC', destination = 'CHI')
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 2318, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/etl_dag.py", line 34, in etl_dag
    departure_date = generate_departure_date(time_delta = time_delta_days)
TypeError: generate_departure_date() got an unexpected keyword argument 'time_delta'
[2023-06-18 16:01:29,065] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 16:01:29,127] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 1.550 seconds
[2023-06-18 16:01:30,454] {scheduler_job.py:182} INFO - Started process (PID=48) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 16:01:30,470] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 16:01:30,481] {logging_mixin.py:104} INFO - [2023-06-18 16:01:30,480] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 16:01:31,170] {logging_mixin.py:104} INFO - [2023-06-18 16:01:31,169] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 16:01:31,386] {logging_mixin.py:104} INFO - [2023-06-18 16:01:31,368] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 40, in <module>
    dag = etl_dag(origin = 'NYC', destination = 'CHI')
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 2318, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/etl_dag.py", line 34, in etl_dag
    departure_date = generate_departure_date(time_delta = time_delta_days)
TypeError: generate_departure_date() got an unexpected keyword argument 'time_delta'
[2023-06-18 16:01:31,390] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 16:01:31,456] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 1.022 seconds
[2023-06-18 16:02:01,642] {scheduler_job.py:182} INFO - Started process (PID=50) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 16:02:01,650] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 16:02:01,653] {logging_mixin.py:104} INFO - [2023-06-18 16:02:01,652] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 16:02:02,176] {logging_mixin.py:104} INFO - [2023-06-18 16:02:02,176] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 16:02:02,384] {logging_mixin.py:104} INFO - [2023-06-18 16:02:02,375] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 40, in <module>
    dag = etl_dag(origin = 'NYC', destination = 'CHI')
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 2318, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/etl_dag.py", line 34, in etl_dag
    departure_date = generate_departure_date(time_delta = time_delta_days)
TypeError: generate_departure_date() got an unexpected keyword argument 'time_delta'
[2023-06-18 16:02:02,387] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 16:02:02,446] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.818 seconds
[2023-06-18 16:02:32,731] {scheduler_job.py:182} INFO - Started process (PID=52) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 16:02:32,738] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 16:02:32,744] {logging_mixin.py:104} INFO - [2023-06-18 16:02:32,740] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 16:02:33,355] {logging_mixin.py:104} INFO - [2023-06-18 16:02:33,355] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 16:02:33,598] {logging_mixin.py:104} INFO - [2023-06-18 16:02:33,586] {dagbag.py:305} ERROR - Failed to import: /opt/airflow/dags/etl_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 302, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/etl_dag.py", line 40, in <module>
    dag = etl_dag(origin = 'NYC', destination = 'CHI')
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dag.py", line 2318, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/etl_dag.py", line 34, in etl_dag
    departure_date = generate_departure_date(time_delta = time_delta_days)
TypeError: generate_departure_date() got an unexpected keyword argument 'time_delta'
[2023-06-18 16:02:33,601] {scheduler_job.py:641} WARNING - No viable dags retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 16:02:33,641] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.923 seconds
[2023-06-18 16:03:03,948] {scheduler_job.py:182} INFO - Started process (PID=54) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 16:03:03,952] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 16:03:03,955] {logging_mixin.py:104} INFO - [2023-06-18 16:03:03,955] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 16:03:04,431] {logging_mixin.py:104} INFO - [2023-06-18 16:03:04,431] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 16:03:04,621] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 16:03:04,736] {logging_mixin.py:104} INFO - [2023-06-18 16:03:04,736] {dag.py:1818} INFO - Sync 1 DAGs
[2023-06-18 16:03:04,792] {logging_mixin.py:104} INFO - [2023-06-18 16:03:04,792] {dag.py:2273} INFO - Setting next_dagrun for etl_dag to None
[2023-06-18 16:03:04,828] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.889 seconds
[2023-06-18 16:03:35,244] {scheduler_job.py:182} INFO - Started process (PID=56) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 16:03:35,250] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 16:03:35,253] {logging_mixin.py:104} INFO - [2023-06-18 16:03:35,253] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 16:03:35,714] {logging_mixin.py:104} INFO - [2023-06-18 16:03:35,714] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 16:03:35,909] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 16:03:36,051] {logging_mixin.py:104} INFO - [2023-06-18 16:03:36,049] {dag.py:1818} INFO - Sync 1 DAGs
[2023-06-18 16:03:36,117] {logging_mixin.py:104} INFO - [2023-06-18 16:03:36,116] {dag.py:2273} INFO - Setting next_dagrun for etl_dag to None
[2023-06-18 16:03:36,145] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.919 seconds
[2023-06-18 16:04:06,574] {scheduler_job.py:182} INFO - Started process (PID=58) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 16:04:06,580] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 16:04:06,583] {logging_mixin.py:104} INFO - [2023-06-18 16:04:06,582] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 16:04:06,987] {logging_mixin.py:104} INFO - [2023-06-18 16:04:06,986] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 16:04:07,164] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 16:04:07,222] {logging_mixin.py:104} INFO - [2023-06-18 16:04:07,221] {dag.py:1818} INFO - Sync 1 DAGs
[2023-06-18 16:04:07,264] {logging_mixin.py:104} INFO - [2023-06-18 16:04:07,264] {dag.py:2273} INFO - Setting next_dagrun for etl_dag to None
[2023-06-18 16:04:07,288] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.731 seconds
[2023-06-18 16:04:37,707] {scheduler_job.py:182} INFO - Started process (PID=60) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 16:04:37,720] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 16:04:37,725] {logging_mixin.py:104} INFO - [2023-06-18 16:04:37,725] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 16:04:38,194] {logging_mixin.py:104} INFO - [2023-06-18 16:04:38,193] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 16:04:38,387] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 16:04:38,451] {logging_mixin.py:104} INFO - [2023-06-18 16:04:38,450] {dag.py:1818} INFO - Sync 1 DAGs
[2023-06-18 16:04:38,502] {logging_mixin.py:104} INFO - [2023-06-18 16:04:38,501] {dag.py:2273} INFO - Setting next_dagrun for etl_dag to None
[2023-06-18 16:04:38,526] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.835 seconds
[2023-06-18 16:05:08,947] {scheduler_job.py:182} INFO - Started process (PID=62) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 16:05:08,951] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 16:05:08,953] {logging_mixin.py:104} INFO - [2023-06-18 16:05:08,953] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 16:05:09,341] {logging_mixin.py:104} INFO - [2023-06-18 16:05:09,341] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 16:05:09,568] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 16:05:09,630] {logging_mixin.py:104} INFO - [2023-06-18 16:05:09,629] {dag.py:1818} INFO - Sync 1 DAGs
[2023-06-18 16:05:09,672] {logging_mixin.py:104} INFO - [2023-06-18 16:05:09,672] {dag.py:2273} INFO - Setting next_dagrun for etl_dag to None
[2023-06-18 16:05:09,692] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.754 seconds
[2023-06-18 16:05:40,054] {scheduler_job.py:182} INFO - Started process (PID=64) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 16:05:40,059] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 16:05:40,063] {logging_mixin.py:104} INFO - [2023-06-18 16:05:40,062] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 16:05:40,491] {logging_mixin.py:104} INFO - [2023-06-18 16:05:40,491] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 16:05:40,662] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 16:05:40,724] {logging_mixin.py:104} INFO - [2023-06-18 16:05:40,724] {dag.py:1818} INFO - Sync 1 DAGs
[2023-06-18 16:05:40,768] {logging_mixin.py:104} INFO - [2023-06-18 16:05:40,767] {dag.py:2273} INFO - Setting next_dagrun for etl_dag to None
[2023-06-18 16:05:40,788] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.748 seconds
[2023-06-18 16:06:11,176] {scheduler_job.py:182} INFO - Started process (PID=66) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 16:06:11,180] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 16:06:11,183] {logging_mixin.py:104} INFO - [2023-06-18 16:06:11,182] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 16:06:11,563] {logging_mixin.py:104} INFO - [2023-06-18 16:06:11,563] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 16:06:11,737] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 16:06:11,783] {logging_mixin.py:104} INFO - [2023-06-18 16:06:11,782] {dag.py:1818} INFO - Sync 1 DAGs
[2023-06-18 16:06:11,825] {logging_mixin.py:104} INFO - [2023-06-18 16:06:11,824] {dag.py:2273} INFO - Setting next_dagrun for etl_dag to None
[2023-06-18 16:06:11,841] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.678 seconds
[2023-06-18 16:06:42,261] {scheduler_job.py:182} INFO - Started process (PID=68) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 16:06:42,264] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 16:06:42,266] {logging_mixin.py:104} INFO - [2023-06-18 16:06:42,266] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 16:06:42,655] {logging_mixin.py:104} INFO - [2023-06-18 16:06:42,655] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 16:06:42,844] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 16:06:42,900] {logging_mixin.py:104} INFO - [2023-06-18 16:06:42,899] {dag.py:1818} INFO - Sync 1 DAGs
[2023-06-18 16:06:42,941] {logging_mixin.py:104} INFO - [2023-06-18 16:06:42,941] {dag.py:2273} INFO - Setting next_dagrun for etl_dag to None
[2023-06-18 16:06:42,966] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.712 seconds
[2023-06-18 16:07:13,322] {scheduler_job.py:182} INFO - Started process (PID=70) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 16:07:13,326] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 16:07:13,328] {logging_mixin.py:104} INFO - [2023-06-18 16:07:13,328] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 16:07:13,697] {logging_mixin.py:104} INFO - [2023-06-18 16:07:13,696] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 16:07:13,865] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 16:07:13,916] {logging_mixin.py:104} INFO - [2023-06-18 16:07:13,916] {dag.py:1818} INFO - Sync 1 DAGs
[2023-06-18 16:07:13,958] {logging_mixin.py:104} INFO - [2023-06-18 16:07:13,958] {dag.py:2273} INFO - Setting next_dagrun for etl_dag to None
[2023-06-18 16:07:13,981] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.666 seconds
[2023-06-18 16:07:44,174] {scheduler_job.py:182} INFO - Started process (PID=72) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 16:07:44,178] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 16:07:44,181] {logging_mixin.py:104} INFO - [2023-06-18 16:07:44,180] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 16:07:44,563] {logging_mixin.py:104} INFO - [2023-06-18 16:07:44,563] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 16:07:44,735] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 16:07:44,795] {logging_mixin.py:104} INFO - [2023-06-18 16:07:44,794] {dag.py:1818} INFO - Sync 1 DAGs
[2023-06-18 16:07:44,845] {logging_mixin.py:104} INFO - [2023-06-18 16:07:44,844] {dag.py:2273} INFO - Setting next_dagrun for etl_dag to None
[2023-06-18 16:07:44,867] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.704 seconds
[2023-06-18 16:08:15,282] {scheduler_job.py:182} INFO - Started process (PID=74) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 16:08:15,286] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 16:08:15,288] {logging_mixin.py:104} INFO - [2023-06-18 16:08:15,288] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 16:08:15,649] {logging_mixin.py:104} INFO - [2023-06-18 16:08:15,648] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 16:08:15,816] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 16:08:15,872] {logging_mixin.py:104} INFO - [2023-06-18 16:08:15,872] {dag.py:1818} INFO - Sync 1 DAGs
[2023-06-18 16:08:15,916] {logging_mixin.py:104} INFO - [2023-06-18 16:08:15,916] {dag.py:2273} INFO - Setting next_dagrun for etl_dag to None
[2023-06-18 16:08:15,941] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.666 seconds
[2023-06-18 16:08:46,382] {scheduler_job.py:182} INFO - Started process (PID=76) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 16:08:46,387] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 16:08:46,390] {logging_mixin.py:104} INFO - [2023-06-18 16:08:46,390] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 16:08:46,792] {logging_mixin.py:104} INFO - [2023-06-18 16:08:46,791] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 16:08:46,963] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 16:08:47,022] {logging_mixin.py:104} INFO - [2023-06-18 16:08:47,021] {dag.py:1818} INFO - Sync 1 DAGs
[2023-06-18 16:08:47,067] {logging_mixin.py:104} INFO - [2023-06-18 16:08:47,067] {dag.py:2273} INFO - Setting next_dagrun for etl_dag to None
[2023-06-18 16:08:47,089] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.721 seconds
[2023-06-18 16:09:17,477] {scheduler_job.py:182} INFO - Started process (PID=78) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 16:09:17,485] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 16:09:17,489] {logging_mixin.py:104} INFO - [2023-06-18 16:09:17,489] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 16:09:17,901] {logging_mixin.py:104} INFO - [2023-06-18 16:09:17,900] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 16:09:18,077] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 16:09:18,139] {logging_mixin.py:104} INFO - [2023-06-18 16:09:18,139] {dag.py:1818} INFO - Sync 1 DAGs
[2023-06-18 16:09:18,188] {logging_mixin.py:104} INFO - [2023-06-18 16:09:18,188] {dag.py:2273} INFO - Setting next_dagrun for etl_dag to None
[2023-06-18 16:09:18,210] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.759 seconds
[2023-06-18 16:09:48,637] {scheduler_job.py:182} INFO - Started process (PID=80) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 16:09:48,649] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 16:09:48,654] {logging_mixin.py:104} INFO - [2023-06-18 16:09:48,653] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 16:09:49,198] {logging_mixin.py:104} INFO - [2023-06-18 16:09:49,198] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 16:09:49,404] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 16:09:49,541] {logging_mixin.py:104} INFO - [2023-06-18 16:09:49,540] {dag.py:1818} INFO - Sync 1 DAGs
[2023-06-18 16:09:49,603] {logging_mixin.py:104} INFO - [2023-06-18 16:09:49,603] {dag.py:2273} INFO - Setting next_dagrun for etl_dag to None
[2023-06-18 16:09:49,622] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 1.009 seconds
[2023-06-18 16:10:20,087] {scheduler_job.py:182} INFO - Started process (PID=82) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 16:10:20,091] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 16:10:20,094] {logging_mixin.py:104} INFO - [2023-06-18 16:10:20,093] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 16:10:20,496] {logging_mixin.py:104} INFO - [2023-06-18 16:10:20,496] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 16:10:20,676] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 16:10:20,764] {logging_mixin.py:104} INFO - [2023-06-18 16:10:20,763] {dag.py:1818} INFO - Sync 1 DAGs
[2023-06-18 16:10:20,813] {logging_mixin.py:104} INFO - [2023-06-18 16:10:20,813] {dag.py:2273} INFO - Setting next_dagrun for etl_dag to None
[2023-06-18 16:10:20,835] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.759 seconds
[2023-06-18 16:10:51,296] {scheduler_job.py:182} INFO - Started process (PID=84) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 16:10:51,305] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 16:10:51,308] {logging_mixin.py:104} INFO - [2023-06-18 16:10:51,307] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 16:10:51,777] {logging_mixin.py:104} INFO - [2023-06-18 16:10:51,776] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 16:10:51,978] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 16:10:52,041] {logging_mixin.py:104} INFO - [2023-06-18 16:10:52,040] {dag.py:1818} INFO - Sync 1 DAGs
[2023-06-18 16:10:52,089] {logging_mixin.py:104} INFO - [2023-06-18 16:10:52,089] {dag.py:2273} INFO - Setting next_dagrun for etl_dag to None
[2023-06-18 16:10:52,110] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.830 seconds
[2023-06-18 16:11:22,506] {scheduler_job.py:182} INFO - Started process (PID=86) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 16:11:22,512] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 16:11:22,516] {logging_mixin.py:104} INFO - [2023-06-18 16:11:22,516] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 16:11:22,923] {logging_mixin.py:104} INFO - [2023-06-18 16:11:22,922] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 16:11:23,112] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 16:11:23,179] {logging_mixin.py:104} INFO - [2023-06-18 16:11:23,178] {dag.py:1818} INFO - Sync 1 DAGs
[2023-06-18 16:11:23,225] {logging_mixin.py:104} INFO - [2023-06-18 16:11:23,225] {dag.py:2273} INFO - Setting next_dagrun for etl_dag to None
[2023-06-18 16:11:23,248] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.753 seconds
[2023-06-18 16:11:53,634] {scheduler_job.py:182} INFO - Started process (PID=88) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 16:11:53,638] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 16:11:53,641] {logging_mixin.py:104} INFO - [2023-06-18 16:11:53,641] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 16:11:54,067] {logging_mixin.py:104} INFO - [2023-06-18 16:11:54,066] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 16:11:54,242] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 16:11:54,302] {logging_mixin.py:104} INFO - [2023-06-18 16:11:54,302] {dag.py:1818} INFO - Sync 1 DAGs
[2023-06-18 16:11:54,347] {logging_mixin.py:104} INFO - [2023-06-18 16:11:54,346] {dag.py:2273} INFO - Setting next_dagrun for etl_dag to None
[2023-06-18 16:11:54,362] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.740 seconds
[2023-06-18 16:12:24,778] {scheduler_job.py:182} INFO - Started process (PID=90) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 16:12:24,783] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 16:12:24,785] {logging_mixin.py:104} INFO - [2023-06-18 16:12:24,785] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 16:12:25,184] {logging_mixin.py:104} INFO - [2023-06-18 16:12:25,183] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 16:12:25,371] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 16:12:25,431] {logging_mixin.py:104} INFO - [2023-06-18 16:12:25,430] {dag.py:1818} INFO - Sync 1 DAGs
[2023-06-18 16:12:25,475] {logging_mixin.py:104} INFO - [2023-06-18 16:12:25,475] {dag.py:2273} INFO - Setting next_dagrun for etl_dag to None
[2023-06-18 16:12:25,507] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.743 seconds
[2023-06-18 16:12:55,959] {scheduler_job.py:182} INFO - Started process (PID=92) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 16:12:55,965] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 16:12:55,969] {logging_mixin.py:104} INFO - [2023-06-18 16:12:55,968] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 16:12:56,399] {logging_mixin.py:104} INFO - [2023-06-18 16:12:56,399] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 16:12:56,568] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 16:12:56,641] {logging_mixin.py:104} INFO - [2023-06-18 16:12:56,641] {dag.py:1818} INFO - Sync 1 DAGs
[2023-06-18 16:12:56,684] {logging_mixin.py:104} INFO - [2023-06-18 16:12:56,684] {dag.py:2273} INFO - Setting next_dagrun for etl_dag to None
[2023-06-18 16:12:56,704] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.761 seconds
[2023-06-18 16:13:27,000] {scheduler_job.py:182} INFO - Started process (PID=94) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 16:13:27,006] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 16:13:27,009] {logging_mixin.py:104} INFO - [2023-06-18 16:13:27,009] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 16:13:27,376] {logging_mixin.py:104} INFO - [2023-06-18 16:13:27,376] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 16:13:27,548] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 16:13:27,605] {logging_mixin.py:104} INFO - [2023-06-18 16:13:27,605] {dag.py:1818} INFO - Sync 1 DAGs
[2023-06-18 16:13:27,646] {logging_mixin.py:104} INFO - [2023-06-18 16:13:27,646] {dag.py:2273} INFO - Setting next_dagrun for etl_dag to None
[2023-06-18 16:13:27,670] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.681 seconds
[2023-06-18 16:13:58,080] {scheduler_job.py:182} INFO - Started process (PID=96) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 16:13:58,085] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 16:13:58,088] {logging_mixin.py:104} INFO - [2023-06-18 16:13:58,088] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 16:13:58,493] {logging_mixin.py:104} INFO - [2023-06-18 16:13:58,492] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 16:13:58,671] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 16:13:58,732] {logging_mixin.py:104} INFO - [2023-06-18 16:13:58,732] {dag.py:1818} INFO - Sync 1 DAGs
[2023-06-18 16:13:58,774] {logging_mixin.py:104} INFO - [2023-06-18 16:13:58,774] {dag.py:2273} INFO - Setting next_dagrun for etl_dag to None
[2023-06-18 16:13:58,795] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.729 seconds
[2023-06-18 16:14:29,027] {scheduler_job.py:182} INFO - Started process (PID=98) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 16:14:29,032] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 16:14:29,035] {logging_mixin.py:104} INFO - [2023-06-18 16:14:29,034] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 16:14:29,433] {logging_mixin.py:104} INFO - [2023-06-18 16:14:29,433] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 16:14:29,603] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 16:14:29,653] {logging_mixin.py:104} INFO - [2023-06-18 16:14:29,653] {dag.py:1818} INFO - Sync 1 DAGs
[2023-06-18 16:14:29,696] {logging_mixin.py:104} INFO - [2023-06-18 16:14:29,696] {dag.py:2273} INFO - Setting next_dagrun for etl_dag to None
[2023-06-18 16:14:29,711] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.696 seconds
[2023-06-18 16:15:00,100] {scheduler_job.py:182} INFO - Started process (PID=100) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 16:15:00,105] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 16:15:00,108] {logging_mixin.py:104} INFO - [2023-06-18 16:15:00,107] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 16:15:00,507] {logging_mixin.py:104} INFO - [2023-06-18 16:15:00,506] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 16:15:00,683] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 16:15:00,762] {logging_mixin.py:104} INFO - [2023-06-18 16:15:00,761] {dag.py:1818} INFO - Sync 1 DAGs
[2023-06-18 16:15:00,808] {logging_mixin.py:104} INFO - [2023-06-18 16:15:00,808] {dag.py:2273} INFO - Setting next_dagrun for etl_dag to None
[2023-06-18 16:15:00,832] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.749 seconds
[2023-06-18 16:15:30,948] {scheduler_job.py:182} INFO - Started process (PID=102) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 16:15:30,952] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 16:15:30,955] {logging_mixin.py:104} INFO - [2023-06-18 16:15:30,955] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 16:15:31,352] {logging_mixin.py:104} INFO - [2023-06-18 16:15:31,351] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 16:15:31,528] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 16:15:31,595] {logging_mixin.py:104} INFO - [2023-06-18 16:15:31,594] {dag.py:1818} INFO - Sync 1 DAGs
[2023-06-18 16:15:31,641] {logging_mixin.py:104} INFO - [2023-06-18 16:15:31,640] {dag.py:2273} INFO - Setting next_dagrun for etl_dag to None
[2023-06-18 16:15:31,683] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.743 seconds
[2023-06-18 16:16:01,953] {scheduler_job.py:182} INFO - Started process (PID=104) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 16:16:01,958] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 16:16:01,962] {logging_mixin.py:104} INFO - [2023-06-18 16:16:01,961] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 16:16:02,373] {logging_mixin.py:104} INFO - [2023-06-18 16:16:02,372] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 16:16:02,554] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 16:16:02,613] {logging_mixin.py:104} INFO - [2023-06-18 16:16:02,613] {dag.py:1818} INFO - Sync 1 DAGs
[2023-06-18 16:16:02,655] {logging_mixin.py:104} INFO - [2023-06-18 16:16:02,654] {dag.py:2273} INFO - Setting next_dagrun for etl_dag to None
[2023-06-18 16:16:02,677] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.733 seconds
[2023-06-18 16:16:33,219] {scheduler_job.py:182} INFO - Started process (PID=106) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 16:16:33,224] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 16:16:33,227] {logging_mixin.py:104} INFO - [2023-06-18 16:16:33,227] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 16:16:33,596] {logging_mixin.py:104} INFO - [2023-06-18 16:16:33,595] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 16:16:33,762] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 16:16:33,818] {logging_mixin.py:104} INFO - [2023-06-18 16:16:33,818] {dag.py:1818} INFO - Sync 1 DAGs
[2023-06-18 16:16:33,871] {logging_mixin.py:104} INFO - [2023-06-18 16:16:33,871] {dag.py:2273} INFO - Setting next_dagrun for etl_dag to None
[2023-06-18 16:16:33,894] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.689 seconds
[2023-06-18 16:17:04,289] {scheduler_job.py:182} INFO - Started process (PID=108) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 16:17:04,294] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 16:17:04,297] {logging_mixin.py:104} INFO - [2023-06-18 16:17:04,297] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 16:17:04,678] {logging_mixin.py:104} INFO - [2023-06-18 16:17:04,678] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 16:17:04,858] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 16:17:04,919] {logging_mixin.py:104} INFO - [2023-06-18 16:17:04,918] {dag.py:1818} INFO - Sync 1 DAGs
[2023-06-18 16:17:04,960] {logging_mixin.py:104} INFO - [2023-06-18 16:17:04,959] {dag.py:2273} INFO - Setting next_dagrun for etl_dag to None
[2023-06-18 16:17:04,980] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.704 seconds
[2023-06-18 16:17:35,207] {scheduler_job.py:182} INFO - Started process (PID=110) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 16:17:35,212] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 16:17:35,214] {logging_mixin.py:104} INFO - [2023-06-18 16:17:35,214] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 16:17:35,591] {logging_mixin.py:104} INFO - [2023-06-18 16:17:35,590] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 16:17:35,762] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 16:17:35,846] {logging_mixin.py:104} INFO - [2023-06-18 16:17:35,846] {dag.py:1818} INFO - Sync 1 DAGs
[2023-06-18 16:17:35,922] {logging_mixin.py:104} INFO - [2023-06-18 16:17:35,921] {dag.py:2273} INFO - Setting next_dagrun for etl_dag to None
[2023-06-18 16:17:35,948] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.751 seconds
[2023-06-18 16:18:06,287] {scheduler_job.py:182} INFO - Started process (PID=112) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 16:18:06,291] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 16:18:06,294] {logging_mixin.py:104} INFO - [2023-06-18 16:18:06,293] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 16:18:06,717] {logging_mixin.py:104} INFO - [2023-06-18 16:18:06,716] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 16:18:06,905] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 16:18:06,993] {logging_mixin.py:104} INFO - [2023-06-18 16:18:06,993] {dag.py:1818} INFO - Sync 1 DAGs
[2023-06-18 16:18:07,044] {logging_mixin.py:104} INFO - [2023-06-18 16:18:07,044] {dag.py:2273} INFO - Setting next_dagrun for etl_dag to None
[2023-06-18 16:18:07,067] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.792 seconds
[2023-06-18 16:18:37,277] {scheduler_job.py:182} INFO - Started process (PID=114) to work on /opt/airflow/dags/etl_dag.py
[2023-06-18 16:18:37,284] {scheduler_job.py:629} INFO - Processing file /opt/airflow/dags/etl_dag.py for tasks to queue
[2023-06-18 16:18:37,287] {logging_mixin.py:104} INFO - [2023-06-18 16:18:37,287] {dagbag.py:448} INFO - Filling up the DagBag from /opt/airflow/dags/etl_dag.py
[2023-06-18 16:18:37,694] {logging_mixin.py:104} INFO - [2023-06-18 16:18:37,693] {credentials.py:1210} INFO - Found credentials in shared credentials file: /usr/local/airflow/.aws/credentials
[2023-06-18 16:18:37,941] {scheduler_job.py:639} INFO - DAG(s) dict_keys(['etl_dag']) retrieved from /opt/airflow/dags/etl_dag.py
[2023-06-18 16:18:38,002] {logging_mixin.py:104} INFO - [2023-06-18 16:18:38,001] {dag.py:1818} INFO - Sync 1 DAGs
[2023-06-18 16:18:38,046] {logging_mixin.py:104} INFO - [2023-06-18 16:18:38,046] {dag.py:2273} INFO - Setting next_dagrun for etl_dag to None
[2023-06-18 16:18:38,091] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/etl_dag.py took 0.830 seconds
